### ISSUE TITLE
Basic customisation

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/cookiecutter-data-science-nesta#1]
- [ ] User name
- [x] Directory names
- [x] Add subdirectory for development notebooks
- [x] Change `src` directory to default to repo name and `setup.py`
- [x] Remove python option

**Comment by bishax** [comment]
Change `src` directory to default to repo name changed in #41b5672

**Comment by bishax** [comment]
Separate issue (#12) opened to discuss naming of `src`

**Comment by bishax** [comment]
Python 3 only added by #15

**Comment by bishax** [comment]
Basic customisation done
