### ISSUE TITLE
bug: module import failure when running notebook preamble

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/cookiecutter-data-science-nesta#30]
I do the following;

1. Install cookiecutter
2. Create virtual environment and install requirements
3. `pip install .`
4. Open Jupyter Lab and run notebook preamble

I get the following:

<img width="599" alt="Screen Shot 2019-09-10 at 12 48 24" src="https://user-images.githubusercontent.com/7520935/64611415-50438400-d3c9-11e9-9010-558a40867929.png">

**Comment by bishax** [comment]
Closing as couldn't reproduce and old issue. 
Please re-open if this persists under latest changes.
