### ISSUE TITLE
Add data getters to requirements?

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/cookiecutter-data-science-nesta#31]
This would make things easier for Nesta personnel working with the cookiecutter but could have implications downstream eg when we make the repos public. Discuss...

**Comment by bishax** [comment]
(Apologies, for some reason I wasn't getting notifications for this repo)

data getters can be added depending on the specific needs of the project, therefore a hard requirement in the cookiecutter is not the right option.
